# Generated by Django 5.0.6 on 2024-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("bio", models.CharField(max_length=40)),
            ],
        ),
    ]
