# Generated by Django 5.0.6 on 2024-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapi", "0002_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="bio",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
