# Generated by Django 5.0.6 on 2024-07-10 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapi", "0003_alter_company_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drfapi.company",
            ),
        ),
    ]
