# Generated by Django 5.0.7 on 2024-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapi", "0004_advocate_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocate",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="images/profile_pic.jpg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
