# Generated by Django 5.0.7 on 2024-07-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapi", "0005_advocate_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocate",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="https://randomuser.me/api/portraits/men/1.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
